name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: adservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/adservice
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/adservice:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: cartservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/cartservice/src
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cartservice:latest

      - name: checkoutservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/checkoutservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/checkoutservice:latest

      - name: currencyservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/currencyservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/currencyservice:latest

      - name: emailservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/emailservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/emailservice:latest

      - name: frontend
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: loadgenerator
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/loadgenerator/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/loadgenerator:latest

      - name: paymentservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/paymentservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/paymentservice:latest

      - name: productcatalogservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/productcatalogservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/productcatalogservice:latest

      - name: recommendationservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/recommendationservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/recommendationservice:latest

      - name: shippingservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/shippingservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shippingservice:latest

      - name: shoppingassistantservice
        uses: docker/build-push-action@v2
        with:
          context: ./case/microservices-demo/src/shoppingassistantservice/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shoppingassistantservice:latest
